/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Secure;

//import javax.swing.JTextField;

import static com.lowagie.text.Annotation.URL;
import java.awt.Dimension;
import java.awt.Frame;
import java.io.InputStream;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Supun
 */
public class MainForm extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void setClientCode(String user) {this.txt_client_code.setText(user);}
    public String getClientCode() {return this.txt_client_code.getText();}

    public void setUserName(String pass) {this.txt_username.setText(pass);}
    public String getUserName() {return this.txt_username.getText();}
    
    public void setFullName(String pass) {this.txt_fullname.setText(pass);}
    public String getFullName() {return this.txt_fullname.getText();}
    
    public void setBLAdmin(String pass) {this.txt_bl_admin.setText(pass);}
    public String getBLAdmin() {return this.txt_bl_admin.getText();}
    /**
     * Creates new form MainForm
     */
    public MainForm() {
    
        initComponents();
        this.setLocationRelativeTo(null);
        
        txt_client_code.setVisible(false);
        txt_username.setVisible(false);
        txt_fullname.setVisible(false);
        txt_bl_admin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_client_code = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        txt_bl_admin = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_bl_no = new javax.swing.JTextField();
        btn_draft = new javax.swing.JButton();
        non_negotiable = new javax.swing.JButton();
        telex_release = new javax.swing.JButton();
        btn_original = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_bc_no = new javax.swing.JTextField();
        bc_print = new javax.swing.JButton();
        release_order_print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Extreme IT Printer App");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_client_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 10, -1));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 10, -1));
        getContentPane().add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 10, -1));
        getContentPane().add(txt_bl_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 10, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bill of Lading No. or ID No.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 15, -1, -1));
        jPanel1.add(txt_bl_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 90, -1));

        btn_draft.setText("BL Draft");
        btn_draft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_draftActionPerformed(evt);
            }
        });
        jPanel1.add(btn_draft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, -1));

        non_negotiable.setText("Non-Negotiable BL");
        non_negotiable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                non_negotiableActionPerformed(evt);
            }
        });
        jPanel1.add(non_negotiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 150, -1));

        telex_release.setText("Telex Release BL");
        telex_release.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telex_releaseActionPerformed(evt);
            }
        });
        jPanel1.add(telex_release, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 150, -1));

        btn_original.setText("Original BL");
        btn_original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_originalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_original, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 140));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 140, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Booking Confirmation No.");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));
        jPanel3.add(txt_bc_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, -1));

        bc_print.setText("Booking Conformation");
        bc_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc_printActionPerformed(evt);
            }
        });
        jPanel3.add(bc_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, -1));

        release_order_print.setText("Release Order");
        release_order_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                release_order_printActionPerformed(evt);
            }
        });
        jPanel3.add(release_order_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_draftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_draftActionPerformed
        String Sql = null;
        conn = MysqlConnect.ConnectDB();
        if(txt_bl_admin.getText().equals("1")){
            
             try{
                Integer.parseInt(txt_bl_no.getText());//number
                Sql = "Select * from bill_of_lading where ID=?";
                }catch(NumberFormatException e){//not number
                Sql = "Select * from bill_of_lading where BL_No=?";    
                }
        }else{
            try{
                Integer.parseInt(txt_bl_no.getText());
                Sql = "Select * from bill_of_lading where ID=? and client_code=?";
            }catch(NumberFormatException e){
                Sql = "Select * from bill_of_lading where BL_No=? and client_code=?";
            }
           
        }
        
         try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1, txt_bl_no.getText());
            
            
            if(txt_bl_admin.getText().equals("0")){
                pst.setString(2, txt_client_code.getText());
            }
            
            rs = pst.executeQuery();
            if(rs.next()){
                InputStream jasperDesign = new URL("http://extremeits.biz/img/bl_draft.jrxml").openStream();
               // InputStream jasperDesign = getClass().getResourceAsStream("bl_draft.jrxml");
                HashMap map = new HashMap();
                String s = rs.getString("BL_No");
                map.put("bl_no",s);
                JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, conn);
                JasperViewer jv = new JasperViewer(jasperPrint, false);
                jv.viewReport(jasperPrint, false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid BL number or this BL number not belongs to you", "Error in BL Number",JOptionPane.ERROR_MESSAGE);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btn_draftActionPerformed

    private void btn_originalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_originalActionPerformed
       String Sql = null;
        conn = MysqlConnect.ConnectDB();
        if(txt_bl_admin.getText().equals("1")){
            try{
                Integer.parseInt(txt_bl_no.getText());//number
                Sql = "Select * from bill_of_lading where ID=?";
                }catch(NumberFormatException e){//not number
                Sql = "Select * from bill_of_lading where BL_No=?";    
                }
        }else{
            try{
                Integer.parseInt(txt_bl_no.getText());
                Sql = "Select * from bill_of_lading where ID=? and client_code=?";
            }catch(NumberFormatException e){
                Sql = "Select * from bill_of_lading where BL_No=? and client_code=?";
            }
        }
        
         try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1, txt_bl_no.getText());
            if(txt_bl_admin.getText().equals("0")){
                pst.setString(2, txt_client_code.getText());
            }
            
            rs = pst.executeQuery();
            if(rs.next()){
                String bl_type = rs.getString("bl_type");
                if(!"Original B/L".equals(bl_type) ){
                JOptionPane.showMessageDialog(null, "Invalid BL type: " + bl_type + ". Try to select different option button");
                return;
                }
                int nos_bls = Integer.parseInt(rs.getString("nos_of_bls"));
                int printed = Integer.parseInt(rs.getString("print"));
                if (nos_bls > printed){
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog (null, "You are about to print BL, which has no print preview before you print.\nMake sure, your printer is switched on and papers are loaded.","Original BL - Print Confirmation",dialogButton);
                    if(dialogResult == JOptionPane.YES_OPTION){
                       
                        //InputStream jasperDesign = getClass().getResourceAsStream("bl_original.javac");
                        InputStream jasperDesign = new URL("http://extremeits.biz/img/bl_original.jrxml").openStream();
                        HashMap map = new HashMap();
                        String s = rs.getString("BL_No");
                        map.put("bl_no",s);
                        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, conn);
                        
                       
                        if(txt_bl_admin.getText().equals("0")){
                            JasperPrintManager.printReport(jasperPrint,false);
                        }else{
                            JasperViewer jv = new JasperViewer(jasperPrint, false);
                            jv.viewReport(jasperPrint, false);
                        }
                        
                        
                        Sql = "UPDATE bill_of_lading SET print=? WHERE BL_No=?";
                        pst = conn.prepareStatement(Sql);
                        
                        printed = printed + 1;
                        
                        pst.setString(1, Integer.toString(printed));
                        pst.setString(2, rs.getString("BL_No"));
                        pst.executeUpdate();
                        conn.close();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "You have exceeded maximum number of original BL prints");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid BL number or this BL number not belongs to you", "Error in BL Number",JOptionPane.ERROR_MESSAGE);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_btn_originalActionPerformed

    private void non_negotiableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_non_negotiableActionPerformed
        String Sql = null;
        conn = MysqlConnect.ConnectDB();
        
        if(txt_bl_admin.getText().equals("1")){
            
             try{
                Integer.parseInt(txt_bl_no.getText());//number
                Sql = "Select * from bill_of_lading where ID=?";
                }catch(NumberFormatException e){//not number
                Sql = "Select * from bill_of_lading where BL_No=?";    
                }
        }else{
            try{
                Integer.parseInt(txt_bl_no.getText());
                Sql = "Select * from bill_of_lading where ID=? and client_code=?";
            }catch(NumberFormatException e){
                Sql = "Select * from bill_of_lading where BL_No=? and client_code=?";
            }
           
        }
        
         try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1, txt_bl_no.getText());
            
            
            if(txt_bl_admin.getText().equals("0")){
                pst.setString(2, txt_client_code.getText());
            }
            
            rs = pst.executeQuery();
            if(rs.next()){
               // InputStream jasperDesign = getClass().getResourceAsStream("non-negotiable.javac");
               InputStream jasperDesign = new URL("http://extremeits.biz/img/non-negotiable.jrxml").openStream();
                HashMap map = new HashMap();
                String s = rs.getString("BL_No");
                map.put("bl_no",s);
                JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, conn);
                JasperViewer jv = new JasperViewer(jasperPrint, false);
                jv.viewReport(jasperPrint, false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid BL number or this BL number not belongs to you", "Error in BL Number",JOptionPane.ERROR_MESSAGE);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }

        
    }//GEN-LAST:event_non_negotiableActionPerformed

    private void telex_releaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telex_releaseActionPerformed
               String Sql = null;
        conn = MysqlConnect.ConnectDB();
        if(txt_bl_admin.getText().equals("1")){
            try{
                Integer.parseInt(txt_bl_no.getText());//number
                Sql = "Select * from bill_of_lading where ID=?";
                }catch(NumberFormatException e){//not number
                Sql = "Select * from bill_of_lading where BL_No=?";    
                }
        }else{
            try{
                Integer.parseInt(txt_bl_no.getText());
                Sql = "Select * from bill_of_lading where ID=? and client_code=?";
            }catch(NumberFormatException e){
                Sql = "Select * from bill_of_lading where BL_No=? and client_code=?";
            }
        }
        
         try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1, txt_bl_no.getText());
            if(txt_bl_admin.getText().equals("0")){
                pst.setString(2, txt_client_code.getText());
            }
            
            rs = pst.executeQuery();
            if(rs.next()){
                String bl_type = rs.getString("bl_type");
                if(!"Telex Release B/L".equals(bl_type) ){
                JOptionPane.showMessageDialog(null, "Invalid BL type: " + bl_type + ". Try to select different option button");
                return;
                }
                int nos_bls = Integer.parseInt(rs.getString("nos_of_bls"));
                int printed = Integer.parseInt(rs.getString("print"));
                if (nos_bls > printed){
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog (null, "You are about to print BL, which has no print preview before you print.\nMake sure, your printer is switched on and papers are loaded.","Telex Release BL - Print Confirmation",dialogButton);
                    if(dialogResult == JOptionPane.YES_OPTION){
                       
                        //InputStream jasperDesign = getClass().getResourceAsStream("telex-release.javac");
                        InputStream jasperDesign = new URL("http://extremeits.biz/img/telex-release.jrxml").openStream();
                        HashMap map = new HashMap();
                        String s = rs.getString("BL_No");
                        map.put("bl_no",s);
                        JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, conn);
                        
                       
                        if(txt_bl_admin.getText().equals("0")){
                            JasperPrintManager.printReport(jasperPrint,false);
                        }else{
                            JasperViewer jv = new JasperViewer(jasperPrint, false);
                            jv.viewReport(jasperPrint, false);
                        }
                        
                        
                        Sql = "UPDATE bill_of_lading SET print=? WHERE BL_No=?";
                        pst = conn.prepareStatement(Sql);
                        
                        printed = printed + 1;
                        
                        pst.setString(1, Integer.toString(printed));
                        pst.setString(2, rs.getString("BL_No"));
                        pst.executeUpdate();
                        conn.close();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "You have exceeded maximum number of Telex Release BL prints");
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid BL number or this BL number not belongs to you", "Error in BL Number",JOptionPane.ERROR_MESSAGE);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_telex_releaseActionPerformed

    private void bc_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc_printActionPerformed
        String Sql = null;
        //JOptionPane.showMessageDialog(null, "ree");
        conn = MysqlConnect.ConnectDB();
        if(txt_bl_admin.getText().equals("1")){
            
             try{
                Integer.parseInt(txt_bc_no.getText());//number
                //JOptionPane.showMessageDialog(null,txt_bc_no.getText());
                Sql = "Select * from booking_confirmation where ID=?";
                }catch(NumberFormatException e){//not number
                Sql = "Select * from booking_confirmation where BC_No=?";    
                }
        }else{
        JOptionPane.showMessageDialog(null, "You are not allowed to view this report");
        return;
    }
        
         try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1, txt_bc_no.getText());
                 
            rs = pst.executeQuery();
            if(rs.next()){
                InputStream jasperDesign = getClass().getResourceAsStream("booking_confirmation.javac");
                HashMap map = new HashMap();
                String s = rs.getString("BC_No");
                map.put("bc_no",s);
                JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, conn);
                JasperViewer jv = new JasperViewer(jasperPrint, false);
                jv.viewReport(jasperPrint, false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Booking Confirmation number or this BC number not belongs to you", "Error in BC Number",JOptionPane.ERROR_MESSAGE);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_bc_printActionPerformed

    private void release_order_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_release_order_printActionPerformed
        String Sql = null;
        //JOptionPane.showMessageDialog(null, "ree");
        conn = MysqlConnect.ConnectDB();
        if(txt_bl_admin.getText().equals("1")){
            
             try{
                Integer.parseInt(txt_bc_no.getText());//number
                //JOptionPane.showMessageDialog(null,txt_bc_no.getText());
                Sql = "Select * from booking_confirmation where ID=?";
                }catch(NumberFormatException e){//not number
                Sql = "Select * from booking_confirmation where BC_No=?";    
                }
        }else{
        JOptionPane.showMessageDialog(null, "You are not allowed to view this report");
        return;
    }
        
         try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1, txt_bc_no.getText());
                 
            rs = pst.executeQuery();
            if(rs.next()){
                InputStream jasperDesign = getClass().getResourceAsStream("release_order.javac");
                HashMap map = new HashMap();
                String s = rs.getString("BC_No");
                map.put("bc_no",s);
                JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, map, conn);
                JasperViewer jv = new JasperViewer(jasperPrint, false);
                jv.viewReport(jasperPrint, false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Booking Confirmation number or this BC number not belongs to you", "Error in BC Number",JOptionPane.ERROR_MESSAGE);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_release_order_printActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bc_print;
    private javax.swing.JButton btn_draft;
    private javax.swing.JButton btn_original;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton non_negotiable;
    private javax.swing.JButton release_order_print;
    private javax.swing.JButton telex_release;
    private javax.swing.JTextField txt_bc_no;
    private javax.swing.JTextField txt_bl_admin;
    private javax.swing.JTextField txt_bl_no;
    private javax.swing.JTextField txt_client_code;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
